# Generated by Django 5.1.6 on 2025-03-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='live_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
