# Generated by Django 5.1.6 on 2025-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flight_live_latitude_flight_live_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
