# Generated by Django 5.1.6 on 2025-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aircraftwithmostflights_daywithmostflights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywithmostflights',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daywithmostflights',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
