# Generated by Django 5.1.6 on 2025-03-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_daywithmostflights_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daywithmostflights',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='daywithmostflights',
            name='longitude',
        ),
        migrations.CreateModel(
            name='AirplaneLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('day_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.daywithmostflights')),
            ],
        ),
    ]
