# Generated by Django 5.1.6 on 2025-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aircraftwithmostflights_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftwithmostflights',
            name='airline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
