# Generated by Django 5.1.6 on 2025-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aircraftwithmostflights_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanelocation',
            name='aircraft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airplanelocation',
            name='airline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airplanelocation',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airplanelocation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
