# Generated by Django 5.1.6 on 2025-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_airplanelocation_aircraft_airplanelocation_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplanelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
